import type { Candidate } from './types';

/**
 * Mirrors `apps/agent/candidateloop/seed.py` so the cockpit renders its real
 * layout before the local API is running. Clearly labelled as preview in the UI;
 * the agent cannot run against it.
 */
export const previewCandidates: Candidate[] = [
  {
    id: 'cand_sarah',
    name: 'Sarah Chen',
    initials: 'SC',
    role: 'Senior Software Engineer',
    stage: 'Technical Interview',
    stage_entered_at: '2026-09-06T09:00:00Z',
    status: 'active',
    last_candidate_contact_at: '2026-09-06T10:00:00Z',
    interview_completed_at: '2026-09-07T15:00:00Z',
    next_interview_at: null,
    required_feedback_count: 4,
    human_decision_status: 'none',
    last_human_resolution: null,
    days_in_stage: 2,
    submitted_feedback_count: 3,
  },
  {
    id: 'cand_david',
    name: 'David Park',
    initials: 'DP',
    role: 'Product Manager',
    stage: 'Recruiter Review',
    stage_entered_at: '2026-09-03T09:00:00Z',
    status: 'active',
    last_candidate_contact_at: '2026-09-03T11:30:00Z',
    interview_completed_at: null,
    next_interview_at: null,
    required_feedback_count: 0,
    human_decision_status: 'none',
    last_human_resolution: null,
    days_in_stage: 5,
    submitted_feedback_count: 0,
  },
  {
    id: 'cand_emily',
    name: 'Emily Jones',
    initials: 'EJ',
    role: 'Senior Software Engineer',
    stage: 'Interview Complete',
    stage_entered_at: '2026-09-07T16:00:00Z',
    status: 'active',
    last_candidate_contact_at: '2026-09-06T14:00:00Z',
    interview_completed_at: '2026-09-07T16:00:00Z',
    next_interview_at: null,
    required_feedback_count: 4,
    human_decision_status: 'none',
    last_human_resolution: null,
    days_in_stage: 1,
    submitted_feedback_count: 4,
  },
  {
    id: 'cand_marcus',
    name: 'Marcus Reed',
    initials: 'MR',
    role: 'Data Engineer',
    stage: 'Technical Interview',
    stage_entered_at: '2026-09-07T10:00:00Z',
    status: 'active',
    last_candidate_contact_at: '2026-09-07T15:00:00Z',
    interview_completed_at: null,
    next_interview_at: '2026-09-09T14:00:00Z',
    required_feedback_count: 3,
    human_decision_status: 'none',
    last_human_resolution: null,
    days_in_stage: 1,
    submitted_feedback_count: 0,
  },
];
